/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PersonalizaRouteImport } from './routes/personaliza'
import { Route as EclipssebrandRouteImport } from './routes/eclipssebrand'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrendasSlugRouteImport } from './routes/prendas.$slug'
import { Route as LegalTerminosRouteImport } from './routes/legal.terminos'
import { Route as LegalPrivacidadRouteImport } from './routes/legal.privacidad'
import { Route as LegalDevolucionesRouteImport } from './routes/legal.devoluciones'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalAvisoLegalRouteImport } from './routes/legal.aviso-legal'

const PersonalizaRoute = PersonalizaRouteImport.update({
  id: '/personaliza',
  path: '/personaliza',
  getParentRoute: () => rootRouteImport,
} as any)
const EclipssebrandRoute = EclipssebrandRouteImport.update({
  id: '/eclipssebrand',
  path: '/eclipssebrand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrendasSlugRoute = PrendasSlugRouteImport.update({
  id: '/prendas/$slug',
  path: '/prendas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTerminosRoute = LegalTerminosRouteImport.update({
  id: '/legal/terminos',
  path: '/legal/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacidadRoute = LegalPrivacidadRouteImport.update({
  id: '/legal/privacidad',
  path: '/legal/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDevolucionesRoute = LegalDevolucionesRouteImport.update({
  id: '/legal/devoluciones',
  path: '/legal/devoluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAvisoLegalRoute = LegalAvisoLegalRouteImport.update({
  id: '/legal/aviso-legal',
  path: '/legal/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eclipssebrand': typeof EclipssebrandRoute
  '/personaliza': typeof PersonalizaRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/devoluciones': typeof LegalDevolucionesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/prendas/$slug': typeof PrendasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eclipssebrand': typeof EclipssebrandRoute
  '/personaliza': typeof PersonalizaRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/devoluciones': typeof LegalDevolucionesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/prendas/$slug': typeof PrendasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eclipssebrand': typeof EclipssebrandRoute
  '/personaliza': typeof PersonalizaRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/devoluciones': typeof LegalDevolucionesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/prendas/$slug': typeof PrendasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eclipssebrand'
    | '/personaliza'
    | '/legal/aviso-legal'
    | '/legal/cookies'
    | '/legal/devoluciones'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/prendas/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eclipssebrand'
    | '/personaliza'
    | '/legal/aviso-legal'
    | '/legal/cookies'
    | '/legal/devoluciones'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/prendas/$slug'
  id:
    | '__root__'
    | '/'
    | '/eclipssebrand'
    | '/personaliza'
    | '/legal/aviso-legal'
    | '/legal/cookies'
    | '/legal/devoluciones'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/prendas/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EclipssebrandRoute: typeof EclipssebrandRoute
  PersonalizaRoute: typeof PersonalizaRoute
  LegalAvisoLegalRoute: typeof LegalAvisoLegalRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDevolucionesRoute: typeof LegalDevolucionesRoute
  LegalPrivacidadRoute: typeof LegalPrivacidadRoute
  LegalTerminosRoute: typeof LegalTerminosRoute
  PrendasSlugRoute: typeof PrendasSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/personaliza': {
      id: '/personaliza'
      path: '/personaliza'
      fullPath: '/personaliza'
      preLoaderRoute: typeof PersonalizaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eclipssebrand': {
      id: '/eclipssebrand'
      path: '/eclipssebrand'
      fullPath: '/eclipssebrand'
      preLoaderRoute: typeof EclipssebrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prendas/$slug': {
      id: '/prendas/$slug'
      path: '/prendas/$slug'
      fullPath: '/prendas/$slug'
      preLoaderRoute: typeof PrendasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terminos': {
      id: '/legal/terminos'
      path: '/legal/terminos'
      fullPath: '/legal/terminos'
      preLoaderRoute: typeof LegalTerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacidad': {
      id: '/legal/privacidad'
      path: '/legal/privacidad'
      fullPath: '/legal/privacidad'
      preLoaderRoute: typeof LegalPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/devoluciones': {
      id: '/legal/devoluciones'
      path: '/legal/devoluciones'
      fullPath: '/legal/devoluciones'
      preLoaderRoute: typeof LegalDevolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/aviso-legal': {
      id: '/legal/aviso-legal'
      path: '/legal/aviso-legal'
      fullPath: '/legal/aviso-legal'
      preLoaderRoute: typeof LegalAvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EclipssebrandRoute: EclipssebrandRoute,
  PersonalizaRoute: PersonalizaRoute,
  LegalAvisoLegalRoute: LegalAvisoLegalRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDevolucionesRoute: LegalDevolucionesRoute,
  LegalPrivacidadRoute: LegalPrivacidadRoute,
  LegalTerminosRoute: LegalTerminosRoute,
  PrendasSlugRoute: PrendasSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
